/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSortRouteImport } from './routes/settings.sort'
import { Route as SettingsBabyRouteImport } from './routes/settings.baby'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSortRoute = SettingsSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBabyRoute = SettingsBabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/baby'
    | '/settings/sort'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/baby'
    | '/settings/sort'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/baby'
    | '/settings/sort'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  StorageRoute: typeof StorageRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sort': {
      id: '/settings/sort'
      path: '/sort'
      fullPath: '/settings/sort'
      preLoaderRoute: typeof SettingsSortRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/baby': {
      id: '/settings/baby'
      path: '/baby'
      fullPath: '/settings/baby'
      preLoaderRoute: typeof SettingsBabyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsBabyRoute: typeof SettingsBabyRoute
  SettingsSortRoute: typeof SettingsSortRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBabyRoute: SettingsBabyRoute,
  SettingsSortRoute: SettingsSortRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  StorageRoute: StorageRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
