/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSortRouteImport } from './routes/settings.sort'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as SettingsBabyEditRouteImport } from './routes/settings.baby.edit'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSortRoute = SettingsSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBabyEditRoute = SettingsBabyEditRouteImport.update({
  id: '/baby/edit',
  path: '/baby/edit',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/baby/edit': typeof SettingsBabyEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/baby/edit': typeof SettingsBabyEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRoute
  '/api/health': typeof ApiHealthRoute
  '/settings/sort': typeof SettingsSortRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/baby/edit': typeof SettingsBabyEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/sort'
    | '/settings/'
    | '/settings/baby/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/sort'
    | '/settings'
    | '/settings/baby/edit'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/settings/sort'
    | '/settings/'
    | '/settings/baby/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  StorageRoute: typeof StorageRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sort': {
      id: '/settings/sort'
      path: '/sort'
      fullPath: '/settings/sort'
      preLoaderRoute: typeof SettingsSortRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/baby/edit': {
      id: '/settings/baby/edit'
      path: '/baby/edit'
      fullPath: '/settings/baby/edit'
      preLoaderRoute: typeof SettingsBabyEditRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSortRoute: typeof SettingsSortRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsBabyEditRoute: typeof SettingsBabyEditRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSortRoute: SettingsSortRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsBabyEditRoute: SettingsBabyEditRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  StorageRoute: StorageRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
